### PR TITLE
Merge branch 'master' into format-client-side

### PR DESCRIPTION
**Pull request by matsuo**

### CODE REVIEW

**Comment by msyk** [comment]
Really? I thought the blanch 'format-client-side' was just working on.

**Comment by matsuo** [comment]
I understand that the branch 'format-client-side' is woking on progress.
I have merged branch 'master' into format-client-side (not merging branch 'format-client-side' into master).

Please see: 
https://github.com/INTER-Mediator/INTER-Mediator/network

**Comment by msyk** [comment]
I see. I thought opposite, and sorry for my mistake. Thanks for supporting.

**Comment by matsuo** [comment]
I'm sorry, too.

**Pull request merged**
