### PR TITLE
VM generation changed.

### PR DESCRIPTION
**Pull request by msyk**
Add chmod for ~developer files, and modified the web root page.

### CODE REVIEW

**Comment by matsuo** [comment]
This pull request includes the data-im-format attribute feature (the commit 9a6e644ea753e81ec09d0f8f077baed2a2c98773).
Is this OK?

**Comment by msyk** [comment]
I haven't intended. I think the data-im-format committing should be separated with this modifications. Is that good way to rebase?

**Comment by matsuo** [comment]
How about "git revert"?

**Comment by msyk** [comment]
How is that?

**Comment by matsuo** [comment]
Thanks.

**Pull request merged**
